### PR TITLE
Add note to vocab_size param

### PR DESCRIPTION
**Pull request by mitjanikolaus**
Explicitly mention that the vocab_size includes the EOS token.

Thanks for working on EGG and opening a PR!
Please fill this template to help us understand what are you introducing in EGG.

## Description
Explicitly mention that the vocab_size includes the EOS token.

## Related Issue (if any)
https://github.com/facebookresearch/EGG/issues/246

## Motivation and Context
https://github.com/facebookresearch/EGG/issues/246

## How Has This Been Tested?
N./A.

### CODE REVIEW

**Comment by robertodessi** [comment]
Hey @mitjanikolaus , thanks for the PR. Once you sign the agreement I'll merge the PR, thanks!

**Comment by mitjanikolaus** [comment]
Ah, that's too bad. I'm afraid I would rather not sign any contract with Facebook. Sorry!

**Comment by robertodessi** [comment]
It's mostly an agreement for any copyright issue, but I understand. I could push the fix and write credits to you if that's ok for you

**Comment by mitjanikolaus** [comment]
That's very kind, thanks for your understanding! So yes, that'd be ok for me :)

**Comment by robertodessi** [comment]
Sure, I'll probably do it sometime this week and thanks! :)

**Comment by mitjanikolaus** [comment]
Added another commit to fix the TransformerSenderReinforce docstring

**Pull request closed without merging**
