### PR TITLE
Adding experiments to zoo

### PR DESCRIPTION
**Pull request by michal-au**
## Description
This code implements the experiments reported in the following paper:

* *Defending Compositionality in Emergent Languages*. Michal Auersperger, Pavel Pecina. NAACL SRW 2022. [[arxiv]](https://arxiv.org/abs/2206.04751)

It is a response to/extension of the experiments implemented in `zoo/compo_vs_generalization`

## How Has This Been Tested?
A typical testing for a research code: no tests at all... Though, I re-run all the experiments just before creating the PR to see if something was off (and it was not!)

### CODE REVIEW

**Comment by robertodessi** [comment]
HI @michal-au,

Thanks a lot for contributing to EGG with your paper. 
We currently try to enforce the usage of black as code formatting style (along with pysort, flake8 and the copyright header).

It seems 4 files are currently failing the black-style check, namely,

- zoo/compo_vs_generalization_ood/archs.py
- zoo/compo_vs_generalization_ood/learning_alone/train.py
- zoo/compo_vs_generalization_ood/train.py
- zoo/compo_vs_generalization_ood/learning_alone/data.py

As soon as you can fix these I'm happy to merge the PR :)

**Comment by robertodessi** [comment]
Hey @michal-au, thanks for fixing the formatting issue. it seems the only thing left now it the copyright header. All files, including `__init__.py` files, should contain a specific header, you can find it in any file in EGG.

Additionally, I seem to understand that you game mostly expand the compo_generalization one and uses symbolic input. We try to add a basic test to check that future commits won't break game logics. You can find an example [here](https://github.com/facebookresearch/EGG/blob/main/tests/test_games_do_not_fail.py#L77-L89). Could you maybe add a test with some dummy but quick and meaningful input?

Thanks!

**Comment by robertodessi** [comment]
It seems the two init file do not pass the black check. Could it be a newline at the end of file?

**Comment by michal-au** [comment]
:partying_face: Thanks @robertodessi for helping out. I found a list of experiments in the main readme so I also updated that if that's fine.

**Comment by robertodessi** [comment]
Sure! Thanks a lot for contributing to EGG! :)

**Pull request merged**
