### PR TITLE
add simple attribute-value dataset and a simple object game

### PR DESCRIPTION
**Pull request by robertodessi**
Proposal to address #63 

- [x] add option to stack distractors

The game is not really needed and was created mostly to debug and test the dataset

### CODE REVIEW

**Comment by eugene-kharitonov** [comment]
Closes https://github.com/facebookresearch/EGG/issues/63

**Comment by robertodessi** [comment]
Should I delete the game?

**Comment by eugene-kharitonov** [comment]
Why deleting? You can add it as an tutorial example in the root README.md and merge. Also wouldn't  hurt also adding to the new UT which check if games are at least running...

**Review by eugene-kharitonov — APPROVED** [review]

**Comment by eugene-kharitonov** [comment]
Cool, thanks @robertodessi !

**Pull request merged**
